#ifndef CUSTOMTRIANGLE_GLOBAL_H
#define CUSTOMTRIANGLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CUSTOMTRIANGLE_LIBRARY)
#  define CUSTOMTRIANGLE_EXPORT Q_DECL_EXPORT
#else
#  define CUSTOMTRIANGLE_EXPORT Q_DECL_IMPORT
#endif

#endif // CUSTOMTRIANGLE_GLOBAL_H
